name: Login to Xserver with Video

on:
  workflow_dispatch:

jobs:
  login-video:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run login script
        env:
          XSERVER_ID: ${{ secrets.XSERVER_ID }}
          XSERVER_PASSWORD: ${{ secrets.XSERVER_PASSWORD }}
        run: node main.mjs

      - name: Convert video to mp4
        run: |
          mkdir -p mp4
          webm=$(find videos -name '*.webm' | head -n 1)
          ffmpeg -i "$webm" -c:v libx264 -preset veryfast -pix_fmt yuv420p mp4/output.mp4

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: login-video
          path: mp4/output.mp4

